---
name: WWW-AtMovies-TV
version: v0.03
author:
  - 'Alec Chen <alec@cpan.org>'
abstract: retrieve TV information from http://www.atmovies.com.tw/
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  HTML::TableExtract: 2.1
  Moose: 0.55
  Test::More: 0
  WWW::Mechanize: 1.34
  version: 0.76
provides:
  WWW::AtMovies::TV:
    file: lib/WWW/AtMovies/TV.pm
    version: v0.03
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
